### ISSUE TITLE
Shared connection closed

### ISSUE THREAD

**Issue by niladribhandari** [mojaloop/interop-devops#4]
While running 
        ansible-playbook create-ec2.yml -e "env=mojaloop"

We are getting issue for mgmt node.

PLAY [Provision management node] ************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************
_**fatal: [mgmt1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 52.48.218.76 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 0}**_
	to retry, use: --limit @/Users/niladrib/Development/Researchwork/interop-devops/create-ec2.retry

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=27   changed=15   unreachable=0    failed=0   
mgmt1                      : ok=0    changed=0    unreachable=0    failed=1

**Comment by elnyry** [comment]
Hi Niladri, we'll look at this and get back to you soon. Thanks for posting!

**Comment by jeffplesko** [comment]
I am assuming from the information presented that you are using an ami different than one of the Ubuntu 14.04 versions.  This was written to work on 14.04 at this time.  The reason for you error is that by default Ubuntu 15+ has python3 installed instead of python.  Chosing 14.04 will be the easiest solution to this problem.  If that is not an option, let me know and we can talk about workarounds that can be done to make the install work with 16.04 but it will require changing the default packages that are installed and specifically setting the ansible interpreter.

**Comment by niladribhandari** [comment]
Thank you very much @jeffplesko 
Could you please let us know the work around to install in ubuntu 16.04. We want to give a try.

Many thanks !!

**Comment by jeffplesko** [comment]
Hello,

I have not completed the workaround for this at the present moment, but so far here are the changes I know that are required:

In the role build_inventory, you will need to add the line below to the build host groups section:

    ansible_python_interpreter: '/usr/bin/python3'

Example:

- name: Build host groups
  add_host:
    hostname: '{{ item.tags.L1Ptype }}{{ item.ami_launch_index|int + 1 }}'
    ansible_hostname: '{{ item.tags.L1Ptype }}{{ item.ami_launch_index|int + 1 }}'
    ansible_host: '{{ item.public_ip_address }}'
    ansible_user: 'ubuntu'
    peer_name: '{{ item.tags.L1Ptype }}{{ item.ami_launch_index|int + 1 }}_peer'
    ansible_ssh_private_key_file: '~/{{ keypair }}.pem'
    ansible_python_interpreter: '/usr/bin/python3' <----add this line
    groups: '{{ item.tags.role }}'
    private_ip: '{{ item.private_ip_address }}'
    instance_id: '{{ item.id }}'
    ec2_facts: '{{ item }}'
  when: subnet.subnets.count > 0
  changed_when: no
  no_log: yes
  with_items: '{{ ec2instances.instances }}'
  register: hostlist
  delegate_to: localhost

And you will also need to adjust the packages which are installed for the worker nodes in the role provision_workers.  See the attached code.

[provision_workers.txt](https://github.com/mojaloop/interop-devops/files/1798723/provision_workers.txt)

You will need to experiment with this some as again, this is not a fully supported install type yet, rather a work in progress.  Let me know if you have questions.

Sincerely,

Jeff Plesko

**Comment by niladribhandari** [comment]
hi @jeffplesko- Thank you a lot. We are using ubuntu 14.04 at the moment. Once we success with this we will go for ubuntu 16.04. we are getting below issue. Could you please help

PLAY [Pull IST ModusBox components] **************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/Users/niladrib/Development/Researchwork/interop-devops/create-ec2.retry

PLAY RECAP ***************************************************************************************************************************************************
dfsp1                      : ok=22   changed=18   unreachable=0    failed=0   
dfsp2                      : ok=22   changed=18   unreachable=0    failed=0   
ist1                       : ok=35   changed=28   unreachable=0    failed=0   
localhost                  : ok=27   changed=11   unreachable=0    failed=1   
mgmt1                      : ok=16   changed=13   unreachable=0    failed=0

**Comment by jeffplesko** [comment]
Hello Again,

Apologies for the delay, I have been out of the office for a few days.  I will need to research how to enable passwordless sudo inside of ansible.  Which AMI from AWS are you using for Ubuntu 14.04 so I can research this issue?

Jeff Plesko

**Comment by niladribhandari** [comment]
Hi Jeff, Yes we are using Ubuntu 14.04.
Thanks
Niladri

**Comment by jeffplesko** [comment]
Please provide the specific ami name/number and the region you are running this in so I can test.  Using the same exact image will be critical to reproducing and solving the issue.  Thank you in advance for the information.

Jeff

**Comment by niladribhandari** [comment]
HI Jeff,
We are using ami-78d2be01 in eu-west-1 region.
instance_type: m4.xlarge
dfsp_ec2_count: 2
ist_ec2_count: 1
mgmt_ec2_count: 1

Thanks
Niladri

**Comment by jeffplesko** [comment]
@niladribhandari 

I have gone through and tested this multiple ways.  The AMI nor the install appears to be the issue and my research has only come up with the possibility that your AWS IAM setup has a custom policy which is turning off the passwordless sudo, which is on by default with AWS.  This is all predicated on the idea that you are using the default installation method which creates the instances for you (meaning that /etc/sudoers file was not manually edited).  I do not have any specifics on the IAM setup.  If you cannot find any details on this, please provide me a sample of your /etc/sudoers file and I can write a custom handler to turn the feature back on for the ubuntu user.

**Comment by niladribhandari** [comment]
@jeffplesko I am able to install successfully. I had to use sudo while executing from mac and copy few config files in subfolders. Thanks a lot for your support. This tool is very useful.
